ignore:
  # Ignore generated files.
  - "**/tl_*_gen.go"
  - "**/rsagen_*.go"
  - "**/*_gen.go"
  - "**/*.gen.go"
  - "**/bindata.go"
  # Ignore commands (examples or internal utilities).
  - "cmd/*/*.go"
  # Ignore testing utilities
  - "telegram/internal/*test/*"

coverage:
  status:
    patch: off
    project:
      default:
        threshold: 0.5%
