ignore:
  # Ignore generated files.
  - "**/tl_*_gen.go"
  - "**/bindata.go"
  # Ignore commands (examples or internal utilities).
  - "cmd/*/*.go"

coverage:
  status:
    patch: off
    project:
      default:
        threshold: 0.5%
