name: Bot
on:
  workflow_dispatch:
    inputs:
      telegram:
        required: true
        description: 'Base64-encoded json payload of command'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log(JSON.stringify(context.payload.inputs))
