---
name: CI
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  # Check if there any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: latest
          args: --timeout 5m
          skip-go-installation: true

  tests-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run tests
        run: go test --timeout 5m ./...
        continue-on-error: true
  tests-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run tests
        run: make test
  tests-on-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.16
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.golang }}-
      - name: Run tests
        run: make test
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.16
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.golang }}-

      - name: Get mtg proxy
        env:
          GO111MODULES: on
        run: go get github.com/gotd/mtg@master && go mod tidy

      - name: Run tests
        env:
          GOTD_TEST_EXTERNAL: 1
          GOTD_MTPROXY_ADDR: "localhost:3128"
        # Run all tests that starts with "TestExternalE2E".
        run: go test -v -run ^TestExternalE2E ./...
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.16
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: coverage-${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            coverage-${{ runner.os }}-go-${{ matrix.golang }}-
      - name: Run tests with coverage
        run: make coverage
      - name: Send coverage
        uses: codecov/codecov-action@v1
        with:
          file: profile.out
  check-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Check that go generate does not make changes
        run: make check_generated
